MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 1231
DATASETS:
  TRAIN: ("lvis_train_cocostyle", )
  TEST: ("lvis_val_cocostyle", )
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  USE_TRANSFER: True
  BASE_LR: 0.02
  IMS_PER_BATCH: 32
  WEIGHT_DECAY: 0.0001
  # WARMUP_ITERS: 0
  STEPS: (30000, 40000)
  MAX_ITER: 45000